version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - JWT_KEY=chaveDocker
      - DATABASE_HOST=lib-manager_postgres_1
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: "postgres"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "libteste"
    command: -p 5431
