version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - JWT_KEY=chaveDocker
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: "postgres"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
