version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - JWT_KEY=chaveDocker
      - DATABASE_HOST=postgres
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: "postgres"
    ports:
<<<<<<< HEAD
      - "5431:5432"
=======
      - "5431:5431"
>>>>>>> bf141388e7601ee5b7b728f1145349464f50e6ec
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
<<<<<<< HEAD
=======
    command: -p 5431
>>>>>>> bf141388e7601ee5b7b728f1145349464f50e6ec
